ERROR - 2023-08-16 01:24:32 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'bdveterinaria' in C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'bdveterinaria', 3306, '', 0)
#1 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\Program Files\Xampp\htdocs\ProyectoFinal\app\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
#7 C:\Program Files\Xampp\htdocs\ProyectoFinal\app\Controllers\Usuarios.php(62): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root')
#8 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
#9 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Program Files\Xampp\htdocs\ProyectoFinal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'bdveterinaria' in C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\Program Files\Xampp\htdocs\ProyectoFinal\app\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
#6 C:\Program Files\Xampp\htdocs\ProyectoFinal\app\Controllers\Usuarios.php(62): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root')
#7 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
#8 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#9 C:\Program Files\Xampp\htdocs\ProyectoFinal\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Program Files\Xampp\htdocs\ProyectoFinal\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-08-16 01:24:32 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'bdveterinaria'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `nombre_usuario` = :nombre_usuario:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Usuarios.php(62): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-08-16 18:05:18 --> syntax error, unexpected identifier "https", expecting ")"
in APPPATH\Views\productos\index.php on line 150.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('productos/index', [], true)
 3 APPPATH\Controllers\Productos.php(15): view('productos/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Productos->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
